name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run format-check
        npm run build
        npm test
      env:
        CI: true
